#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# Run SmartOS user-script
#

set -o xtrace

. /lib/svc/share/smf_include.sh

cd /
export PATH=/opt/custom/bin:/usr/sbin:/usr/bin

case "$1" in
'start')
    mdata-get user-script > /var/svc/mdata-user-script
    if [[ $? -eq 0 ]]; then
        chmod 755 /var/svc/mdata-user-script
        /var/svc/mdata-user-script
        if [[ $? -ne 0 ]]; then
            exit $SMF_EXIT_ERR_FATAL
        fi
    fi
    ;;
*)
    echo "Usage: $0 { start }"
    exit $SMF_EXIT_ERR_FATAL
    ;;
esac
exit $SMF_EXIT_OK

