#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2021 Joyent, Inc.
#

#
# Setup SmartOS GZ for running dumb NAT zones
#

set -o xtrace

. /lib/svc/share/smf_include.sh

cd /
export PATH=/opt/custom/bin:/usr/sbin:/usr/bin

case "$1" in
'start')
    # Hostname!
    hostname=$(. /usbkey/config ; echo ${hostname} | tr '.' '_')
    if [[ -n ${hostname} ]]; then
         hostname "${hostname}" && hostname > /etc/nodename
    fi

    # Don't need Ur
    svcadm disable svc:/smartdc/agent/ur:default || /bin/true

    # Don't need mDNS spewing errors
    svcadm disable svc:/network/dns/multicast:default || /bin/true

    # NOPE
    svcadm disable svc:/network/smtp:sendmail svc:/network/sendmail-client:default
    for i in $(seq 2 6); do svcadm disable svc:/system/console-login:vt${i}; done
    svcadm disable svc:/system/smartdc/vmadmd:default

    # Setup dotfiles and root's homedir
    if [[ -d /opt/custom/root ]]; then
        rm -rf /root && ln -s /opt/custom/root /root
    fi

    # add any missing keys from root_authorized_keys
    if mdata-get root_authorized_keys >/root/.ssh/authorized_keys.new; then
        cp /root/.ssh/authorized_keys /root/.ssh/authorized_keys.old
        cat /root/.ssh/authorized_keys.{new,old} | sort \
            | grep -E '^(ssh|ecdsa)' | uniq \
            > /root/.ssh/authorized_keys.replacement
        mv /root/.ssh/authorized_keys.replacement /root/.ssh/authorized_keys
        rm -f /root/.ssh/authorized_keys.{new,old}
    fi

    ;;

*)
    echo "Usage: $0 { start }"
    exit $SMF_EXIT_ERR_FATAL
    ;;
esac
exit $SMF_EXIT_OK

